name = input("whats ur name?")
print(f"letters in name: {len(name)}")
print(f"First letter : {name[1]}")
print(f"Last letter : {name[-1]}")
print(f"Reverse Name: {name[::-1]} ")
text= input("Write word: ")
print(text.upper())
print(text.lower())
print(text.title())
